import type { ComponentType } from "react";
import {
  AuditLogsPage,
  NotificationSettingsPage,
  PermissionsPage,
  RoleGroupsPage,
  RolesPage,
  SystemSettingsPage,
  UserFormPage,
  UsersPage,
} from "@/features/admin/pages/AdminPages";
import {
  CustomerActivityPage,
  CustomerDetailPage,
  CustomerFormPage,
  CustomerGroupsPage,
  CustomerListPage,
} from "@/features/customers/pages/CustomerPages";
import { DashboardPage } from "@/features/dashboard/pages/DashboardPage";
import {
  DeliveryCalendarPage,
  DeliveryDetailPage,
  DeliveryFormPage,
  DeliveryListPage,
  DispatchPage,
  ProofOfDeliveryPage,
} from "@/features/delivery/pages/DeliveryPages";
import {
  InventoryFormPage,
  InventoryListPage,
  LowStockPage,
  StockMovementsPage,
  StockOverviewPage,
  UnitsOfMeasurePage,
} from "@/features/inventory/pages/InventoryPages";
import {
  ManufacturingJobDetailPage,
  ManufacturingJobFormPage,
  ManufacturingJobsPage,
  MaterialRequirementsPage,
  ProductionBoardPage,
  ProductionTrackingPage,
  QualityInspectionPage,
  ReadyToShipPage,
  WorkOrdersPage,
} from "@/features/manufacturing/pages/ManufacturingPages";
import {
  BrandsPage,
  CategoriesPage,
  PriceListsPage,
  ProductAttributesPage,
  ProductDetailPage,
  ProductFormPage,
  ProductListPage,
} from "@/features/products/pages/ProductPages";
import {
  EstimateFormPage,
  QuotationPreviewPage,
  QuotationWorkspacePage,
  SalesOrderDetailPage,
  SalesOrderFormPage,
  SalesOrderWorkspacePage,
  SalesOrderReviewPage,
  InvoicesPage,
  PaymentsPage,
} from "@/features/sales/pages/SalesPages";
import { FinanceInvoicesPage, FinanceCreditNotesPage } from "@/features/finance/pages/FinancePages";
import { CostingApprovalWorkspacePage } from "@/features/costing/pages/CostingApprovalWorkspacePage";
import { CoatingRequestsWorkspacePage } from "@/features/costing/pages/CoatingRequestsWorkspacePage";
import { NotFoundPage } from "@/features/shared/pages/NotFoundPage";

export const PAGE_REGISTRY = {
  DashboardPage,
  QuotationWorkspacePage,
  EstimateFormPage,
  QuotationPreviewPage,
  CostingApprovalWorkspacePage,
  CoatingRequestsWorkspacePage,
  SalesOrderWorkspacePage,
  SalesOrderFormPage,
  SalesOrderReviewPage,
  SalesOrderDetailPage,
  PaymentsPage,
  InvoicesPage,
  FinanceInvoicesPage,
  FinanceCreditNotesPage,
  CustomerListPage,
  CustomerFormPage,
  CustomerGroupsPage,
  CustomerActivityPage,
  CustomerDetailPage,
  ProductListPage,
  ProductFormPage,
  CategoriesPage,
  BrandsPage,
  ProductAttributesPage,
  PriceListsPage,
  ProductDetailPage,
  InventoryListPage,
  InventoryFormPage,
  StockOverviewPage,
  StockMovementsPage,
  LowStockPage,
  UnitsOfMeasurePage,
  ProductionTrackingPage,
  ReadyToShipPage,
  ManufacturingJobFormPage,
  ManufacturingJobDetailPage,
  ManufacturingJobsPage,
  WorkOrdersPage,
  ProductionBoardPage,
  MaterialRequirementsPage,
  QualityInspectionPage,
  DeliveryListPage,
  DeliveryFormPage,
  DeliveryCalendarPage,
  DispatchPage,
  ProofOfDeliveryPage,
  DeliveryDetailPage,
  UserFormPage,
  UsersPage,
  RolesPage,
  RoleGroupsPage,
  PermissionsPage,
  SystemSettingsPage,
  NotificationSettingsPage,
  AuditLogsPage,
  NotFoundPage,
} as const satisfies Record<string, ComponentType>;

export type PageKey = keyof typeof PAGE_REGISTRY;
