import type { CostingRequest } from "@/types/costing";

export function mapCosting(raw: Record<string, unknown>): CostingRequest {
  return {
    id: String(raw.id),
    requestNumber: String(raw.requestNumber ?? ""),
    customerName: String(raw.customerName ?? ""),
    projectName: String(raw.projectName ?? ""),
    requestType: String(raw.requestType ?? ""),
    requestedDate: String(raw.requestedDate ?? new Date().toISOString()),
    totalEstimate: Number(raw.totalEstimate ?? 0),
    proposedPrice: Number(raw.proposedPrice ?? 0),
    marginPercent: Number(raw.marginPercent ?? 0),
    targetMargin: Number(raw.targetMargin ?? 0),
    riskFlag: (raw.riskFlag as CostingRequest["riskFlag"]) ?? "medium",
    slaRemaining: String(raw.slaRemaining ?? ""),
    status: (raw.status as CostingRequest["status"]) ?? "pending",
    coatingStatus: (raw.coatingStatus as CostingRequest["coatingStatus"]) ?? "pending",
    currency: String(raw.currency ?? "LKR"),
    paymentTerms: String(raw.paymentTerms ?? ""),
    lineItems: (raw.lineItems as CostingRequest["lineItems"]) ?? [],
    coatingItems: (raw.coatingItems as CostingRequest["coatingItems"]) ?? [],
    estimationMaterials: (raw.estimationMaterials as CostingRequest["estimationMaterials"]) ?? [],
    estimationProductLines: (raw.estimationProductLines as CostingRequest["estimationProductLines"]) ?? [],
    attachments: (raw.attachments as CostingRequest["attachments"]) ?? [],
    notes: String(raw.notes ?? ""),
    requester: (raw.requester as CostingRequest["requester"]) ?? {
      name: "",
      title: "",
      email: "",
      avatarInitials: "",
    },
    approvalLevels: (raw.approvalLevels as CostingRequest["approvalLevels"]) ?? [],
    history: (raw.history as CostingRequest["history"]) ?? [],
    salesOrderId: raw.salesOrderId == null ? undefined : String(raw.salesOrderId),
    salesOrderNumber: raw.salesOrderNumber as string | undefined,
    quotationId: raw.quotationId == null ? undefined : String(raw.quotationId),
    quotationNumber: raw.quotationNumber as string | undefined,
    workflowDefinitionId: raw.workflowDefinitionId as string | undefined,
    workflowVersionId: raw.workflowVersionId as string | undefined,
    workflowInstanceId: raw.workflowInstanceId as string | undefined,
    workflowVersionNumber: raw.workflowVersionNumber as number | undefined,
    workflowName: raw.workflowName as string | undefined,
  };
}
