import type { ManufacturingJob } from "@/types/manufacturing";

export function mapManufacturingJob(raw: Record<string, unknown>): ManufacturingJob {
  return {
    id: String(raw.id),
    jobNumber: String(raw.jobNumber ?? ""),
    salesOrderId: String(raw.salesOrderId),
    salesOrderNumber: String(raw.salesOrderNumber ?? ""),
    customerId: String(raw.customerId),
    customerName: String(raw.customerName ?? ""),
    productId: String(raw.productId),
    productSku: String(raw.productSku ?? ""),
    productName: String(raw.productName ?? ""),
    productVersionId: String(raw.productVersionId ?? ""),
    productVersionLabel: String(raw.productVersionLabel ?? ""),
    quantity: Number(raw.quantity ?? 0),
    status: (raw.status as ManufacturingJob["status"]) ?? "draft",
    priority: (raw.priority as ManufacturingJob["priority"]) ?? "medium",
    tasks: (raw.tasks as ManufacturingJob["tasks"]) ?? [],
    reworks: (raw.reworks as ManufacturingJob["reworks"]) ?? [],
    materialRequirements: (raw.materialRequirements as ManufacturingJob["materialRequirements"]) ?? [],
    qualityInspection: raw.qualityInspection as ManufacturingJob["qualityInspection"],
    plannedStartDate: String(raw.plannedStartDate ?? new Date().toISOString()),
    plannedEndDate: String(raw.plannedEndDate ?? new Date().toISOString()),
    actualStartDate: raw.actualStartDate as string | undefined,
    actualEndDate: raw.actualEndDate as string | undefined,
    progressPercent: Number(raw.progressPercent ?? 0),
    estimatedCost: Number(raw.estimatedCost ?? 0),
    actualCost: Number(raw.actualCost ?? 0),
    assignedTo: raw.assignedTo == null ? undefined : String(raw.assignedTo),
    assignedToName: raw.assignedToName as string | undefined,
    notes: raw.notes as string | undefined,
    materialOutcome: raw.materialOutcome as ManufacturingJob["materialOutcome"],
    createdBy: String(raw.createdBy ?? ""),
    createdByName: String(raw.createdByName ?? ""),
    createdAt: String(raw.createdAt ?? new Date().toISOString()),
    updatedAt: String(raw.updatedAt ?? new Date().toISOString()),
  };
}
