import type { ReportCategory, ReportColumn, ReportDefinition, ReportId } from "@/types/report";

function col(
  key: string,
  label: string,
  type: ReportColumn["type"] = "text",
  align?: ReportColumn["align"],
): ReportColumn {
  return {
    key,
    label,
    type,
    align: align ?? (type === "number" || type === "currency" || type === "percent" ? "right" : "left"),
  };
}

export const REPORT_CATEGORY_LABELS: Record<ReportCategory, string> = {
  sales: "Sales",
  operations: "Costing & Estimation",
  production: "Production",
  inventory: "Inventory & Reprocessing",
  finance: "Finance",
  delivery: "Delivery",
  customers: "Customers",
  products: "Products",
  admin: "Administration",
};

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: "quotation-register",
    title: "Quotation Register",
    description: "All quotations with status, value, validity, and conversion to sales orders.",
    category: "sales",
    icon: "FileText",
    permission: "quotations:view",
    sources: ["quotations"],
    dateKey: "createdAt",
    columns: [
      col("quotationNumber", "Quotation"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("lineCount", "Lines", "number"),
      col("totalAmount", "Total", "currency"),
      col("paymentStatus", "Payment", "status"),
      col("validUntil", "Valid until", "date"),
      col("salesOrderId", "Sales order"),
      col("createdByName", "Created by"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "quotation-conversion",
    title: "Quotation Conversion",
    description: "Pipeline by status, accepted value, and conversion from quote to sales order.",
    category: "sales",
    icon: "BarChart3",
    permission: "quotations:view",
    sources: ["quotations"],
    columns: [
      col("status", "Status", "status"),
      col("count", "Quotations", "number"),
      col("totalAmount", "Value", "currency"),
      col("sharePercent", "Share", "percent"),
    ],
  },
  {
    id: "quotation-follow-up",
    title: "Quotation Follow-up",
    description: "Contact history across quotations - calls, emails, meetings, and outcomes.",
    category: "sales",
    icon: "FileText",
    permission: "quotations:view",
    sources: ["quotations"],
    dateKey: "contactedAt",
    columns: [
      col("quotationNumber", "Quotation"),
      col("customerName", "Customer"),
      col("type", "Type", "status"),
      col("summary", "Summary"),
      col("outcome", "Outcome"),
      col("contactedByName", "Contacted by"),
      col("contactedAt", "Contacted", "datetime"),
    ],
  },
  {
    id: "sales-order-register",
    title: "Sales Order Register",
    description: "All sales orders with status, payment, linked quotation, and manufacturing jobs.",
    category: "sales",
    icon: "ClipboardList",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    dateKey: "createdAt",
    columns: [
      col("orderNumber", "Order"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("quotationNumber", "Quotation"),
      col("totalAmount", "Total", "currency"),
      col("paymentStatus", "Payment", "status"),
      col("jobCount", "Jobs", "number"),
      col("requestedDeliveryDate", "Requested delivery", "date"),
      col("assignedToName", "Assigned to"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "sales-order-fulfillment",
    title: "Order Fulfillment",
    description: "Line-level ordered vs in manufacturing vs delivered quantities.",
    category: "sales",
    icon: "PackageCheck",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    columns: [
      col("orderNumber", "Order"),
      col("customerName", "Customer"),
      col("productSku", "SKU"),
      col("productName", "Product"),
      col("quantity", "Ordered", "number"),
      col("quantityInManufacturing", "In production", "number"),
      col("quantityDelivered", "Delivered", "number"),
      col("quantityOpen", "Open", "number"),
      col("fulfillmentPercent", "Fulfilled", "percent"),
    ],
  },
  {
    id: "sales-by-customer",
    title: "Sales by Customer",
    description: "Confirmed order value, order count, and outstanding payment by customer.",
    category: "sales",
    icon: "Users",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    columns: [
      col("customerName", "Customer"),
      col("orderCount", "Orders", "number"),
      col("totalAmount", "Order value", "currency"),
      col("unpaidAmount", "Unpaid / partial", "currency"),
      col("openOrders", "Open orders", "number"),
    ],
  },
  {
    id: "sales-by-product",
    title: "Sales by Product",
    description: "Quantities and revenue by product from sales order lines.",
    category: "sales",
    icon: "Package",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    columns: [
      col("productSku", "SKU"),
      col("productName", "Product"),
      col("orderCount", "Orders", "number"),
      col("quantity", "Qty ordered", "number"),
      col("quantityDelivered", "Qty delivered", "number"),
      col("lineTotal", "Revenue", "currency"),
    ],
  },
  {
    id: "open-sales-orders",
    title: "Open Sales Orders",
    description: "Orders not yet completed, delivered, or cancelled - the live sales backlog.",
    category: "sales",
    icon: "ClipboardList",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    dateKey: "createdAt",
    columns: [
      col("orderNumber", "Order"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("totalAmount", "Total", "currency"),
      col("paymentStatus", "Payment", "status"),
      col("requestedDeliveryDate", "Requested delivery", "date"),
      col("jobCount", "Jobs", "number"),
    ],
  },
  {
    id: "costing-register",
    title: "Costing Request Register",
    description: "Estimation and approval requests with margin, risk, coating, and SLA.",
    category: "operations",
    icon: "Calculator",
    permission: "quotations:view",
    sources: ["costing"],
    dateKey: "requestedDate",
    columns: [
      col("requestNumber", "Request"),
      col("customerName", "Customer"),
      col("projectName", "Project"),
      col("status", "Status", "status"),
      col("riskFlag", "Risk", "status"),
      col("coatingStatus", "Coating", "status"),
      col("totalEstimate", "Estimate", "currency"),
      col("proposedPrice", "Proposed price", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("targetMargin", "Target margin", "percent"),
      col("salesOrderNumber", "Sales order"),
      col("slaRemaining", "SLA"),
    ],
  },
  {
    id: "costing-margin",
    title: "Margin & Risk Analysis",
    description: "Proposed vs target margin, estimate-to-price gap, and high-risk costing requests.",
    category: "operations",
    icon: "Calculator",
    permission: "quotations:view",
    sources: ["costing"],
    columns: [
      col("requestNumber", "Request"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("riskFlag", "Risk", "status"),
      col("totalEstimate", "Cost estimate", "currency"),
      col("proposedPrice", "Proposed price", "currency"),
      col("marginAmount", "Margin amount", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("targetMargin", "Target", "percent"),
      col("marginGap", "Vs target", "percent"),
    ],
  },
  {
    id: "estimation-materials",
    title: "Estimation Material Requirements",
    description: "BOM-style materials from product estimation, including waste and line cost.",
    category: "operations",
    icon: "Layers",
    permission: "quotations:view",
    sources: ["costing"],
    columns: [
      col("requestNumber", "Request"),
      col("customerName", "Customer"),
      col("sku", "SKU"),
      col("inventoryItemName", "Material"),
      col("sourceProductName", "For product"),
      col("quantity", "Qty", "number"),
      col("wastePercent", "Waste", "percent"),
      col("requiredQuantity", "Required", "number"),
      col("unit", "Unit"),
      col("unitCost", "Unit cost", "currency"),
      col("totalCost", "Line cost", "currency"),
    ],
  },
  {
    id: "coating-costs",
    title: "Coating Cost Report",
    description: "Coating and finishing lines from estimation - finish, process, quantity, and cost.",
    category: "operations",
    icon: "Layers",
    permission: "quotations:view",
    sources: ["costing"],
    columns: [
      col("requestNumber", "Request"),
      col("productName", "Product"),
      col("productSku", "SKU"),
      col("finish", "Finish"),
      col("process", "Process"),
      col("quantity", "Qty", "number"),
      col("unitCost", "Unit cost", "currency"),
      col("lineTotal", "Line total", "currency"),
      col("coatingStatus", "Coating status", "status"),
    ],
  },
  {
    id: "customization-approvals",
    title: "Customization Approvals",
    description: "Quotation product customizations with estimation, margin, and approval status.",
    category: "operations",
    icon: "FileCheck",
    permission: "quotations:view",
    sources: ["quotations"],
    dateKey: "updatedAt",
    columns: [
      col("quotationNumber", "Quotation"),
      col("customerName", "Customer"),
      col("productSku", "SKU"),
      col("productName", "Product"),
      col("status", "Status", "status"),
      col("costPrice", "Cost", "currency"),
      col("sellingPrice", "Selling", "currency"),
      col("expectedProfit", "Profit", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("approvalStatus", "Approval", "status"),
      col("decidedByName", "Decided by"),
    ],
  },
  {
    id: "production-jobs",
    title: "Production Job Register",
    description: "All production jobs with progress, dates, cost, and assignment.",
    category: "production",
    icon: "Factory",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "plannedStartDate",
    columns: [
      col("jobNumber", "Job"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("productSku", "SKU"),
      col("productName", "Product"),
      col("quantity", "Qty", "number"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("progressPercent", "Progress", "percent"),
      col("estimatedCost", "Estimated cost", "currency"),
      col("actualCost", "Actual cost", "currency"),
      col("plannedEndDate", "Due", "date"),
      col("assignedToName", "Supervisor"),
    ],
  },
  {
    id: "production-wip",
    title: "WIP & Delayed Jobs",
    description: "Jobs in progress, on hold, or overdue against the planned end date.",
    category: "production",
    icon: "AlertTriangle",
    permission: "manufacturing:view",
    sources: ["jobs"],
    columns: [
      col("jobNumber", "Job"),
      col("customerName", "Customer"),
      col("productName", "Product"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("progressPercent", "Progress", "percent"),
      col("currentTask", "Current task"),
      col("plannedEndDate", "Due", "date"),
      col("overdueDays", "Overdue days", "number"),
      col("assignedToName", "Supervisor"),
    ],
  },
  {
    id: "production-cost-variance",
    title: "Production Cost Variance",
    description: "Estimated vs actual job cost, including labor, machine, material, and rework.",
    category: "production",
    icon: "Calculator",
    permission: "manufacturing:view",
    sources: ["jobs"],
    columns: [
      col("jobNumber", "Job"),
      col("productName", "Product"),
      col("status", "Status", "status"),
      col("estimatedCost", "Estimated", "currency"),
      col("actualCost", "Actual", "currency"),
      col("laborCost", "Labor", "currency"),
      col("variance", "Variance", "currency"),
      col("variancePercent", "Variance %", "percent"),
    ],
  },
  {
    id: "labor-hours-cost",
    title: "Labor Hours & Cost",
    description: "Regular vs overtime hours and cost by production job using system labor rates.",
    category: "production",
    icon: "Factory",
    permission: "manufacturing:view",
    sources: ["jobs"],
    columns: [
      col("jobNumber", "Job"),
      col("productName", "Product"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("actualHours", "Actual hours", "number"),
      col("regularHours", "Regular hours", "number"),
      col("overtimeHours", "OT hours", "number"),
      col("regularCost", "Regular cost", "currency"),
      col("overtimeCost", "OT cost", "currency"),
      col("laborCost", "Labor cost", "currency"),
    ],
  },
  {
    id: "task-performance",
    title: "Task Performance",
    description: "Operation-level hours, quantities, rejects, waste, and workstation.",
    category: "production",
    icon: "Cog",
    permission: "manufacturing:view",
    sources: ["jobs"],
    columns: [
      col("jobNumber", "Job"),
      col("taskNumber", "Task"),
      col("name", "Operation"),
      col("workstation", "Workstation"),
      col("status", "Status", "status"),
      col("estimatedHours", "Est. hours", "number"),
      col("actualHours", "Actual hours", "number"),
      col("overtimeHours", "OT hours", "number"),
      col("plannedQuantity", "Planned qty", "number"),
      col("completedQuantity", "Completed", "number"),
      col("rejectedQuantity", "Rejected", "number"),
      col("wasteQuantity", "Waste", "number"),
      col("operatorName", "Operator"),
    ],
  },
  {
    id: "quality-inspections",
    title: "Quality Inspection Report",
    description: "QC results, inspector, checklist pass rate, and linked production job.",
    category: "production",
    icon: "ShieldCheck",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "inspectedAt",
    columns: [
      col("jobNumber", "Job"),
      col("inspectionNumber", "Inspection"),
      col("productName", "Product"),
      col("customerName", "Customer"),
      col("status", "Result", "status"),
      col("inspectorName", "Inspector"),
      col("checklistTotal", "Checks", "number"),
      col("checklistPassed", "Passed", "number"),
      col("passRate", "Pass rate", "percent"),
      col("inspectedAt", "Inspected", "datetime"),
      col("notes", "Notes"),
    ],
  },
  {
    id: "rework-register",
    title: "Rework Register",
    description: "Rework loops with reason, quantity, extra time, extra cost, and result.",
    category: "production",
    icon: "Wrench",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "createdAt",
    columns: [
      col("jobNumber", "Job"),
      col("reworkNumber", "Rework"),
      col("productName", "Product"),
      col("reason", "Reason"),
      col("quantity", "Qty", "number"),
      col("additionalTimeHours", "Extra hours", "number"),
      col("additionalCost", "Extra cost", "currency"),
      col("result", "Result", "status"),
      col("createdAt", "Created", "date"),
      col("completedAt", "Completed", "date"),
    ],
  },
  {
    id: "scrap-waste",
    title: "Scrap, Waste & Yield",
    description: "Finished output, reusable scrap, recoverable qty, and permanent waste by job.",
    category: "production",
    icon: "Flame",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "postedAt",
    columns: [
      col("jobNumber", "Job"),
      col("productName", "Product"),
      col("plannedQuantity", "Planned", "number"),
      col("finishedMaterialQuantity", "Finished", "number"),
      col("reusableScrapQuantity", "Reusable scrap", "number"),
      col("recoverableQuantity", "Recoverable", "number"),
      col("permanentWasteQuantity", "Permanent waste", "number"),
      col("yieldPercent", "Yield", "percent"),
      col("postedAt", "Posted", "date"),
    ],
  },
  {
    id: "material-requirements",
    title: "Material Requirements & Issue",
    description: "Required vs reserved vs issued materials for production jobs.",
    category: "production",
    icon: "PackageSearch",
    permission: "manufacturing:view",
    sources: ["jobs"],
    columns: [
      col("jobNumber", "Job"),
      col("productName", "Product"),
      col("inventoryItemSku", "SKU"),
      col("inventoryItemName", "Material"),
      col("requiredQuantity", "Required", "number"),
      col("reservedQuantity", "Reserved", "number"),
      col("issuedQuantity", "Issued", "number"),
      col("shortfall", "Shortfall", "number"),
      col("unit", "Unit"),
      col("status", "Status", "status"),
      col("issuedUnitCost", "Unit cost", "currency"),
    ],
  },
  {
    id: "ready-to-ship",
    title: "Ready to Ship",
    description: "Completed production jobs cleared for dispatch.",
    category: "production",
    icon: "PackageCheck",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "actualEndDate",
    columns: [
      col("jobNumber", "Job"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("productName", "Product"),
      col("quantity", "Qty", "number"),
      col("actualEndDate", "Completed", "date"),
      col("actualCost", "Actual cost", "currency"),
    ],
  },
  {
    id: "stock-valuation",
    title: "Stock On Hand & Valuation",
    description: "On-hand, reserved, and available quantities with inventory value at cost.",
    category: "inventory",
    icon: "Warehouse",
    permission: "inventory:view",
    sources: ["inventory"],
    columns: [
      col("sku", "SKU"),
      col("name", "Item"),
      col("itemType", "Type", "status"),
      col("warehouse", "Warehouse"),
      col("location", "Location"),
      col("quantityOnHand", "On hand", "number"),
      col("quantityReserved", "Reserved", "number"),
      col("quantityAvailable", "Available", "number"),
      col("unit", "Unit"),
      col("costPrice", "Cost", "currency"),
      col("stockValue", "Stock value", "currency"),
      col("stockStatus", "Stock status", "status"),
    ],
  },
  {
    id: "low-stock",
    title: "Low Stock & Reorder",
    description: "Items at or below reorder level, with suggested reorder quantity.",
    category: "inventory",
    icon: "AlertTriangle",
    permission: "inventory:view",
    sources: ["inventory"],
    columns: [
      col("sku", "SKU"),
      col("name", "Item"),
      col("warehouse", "Warehouse"),
      col("quantityAvailable", "Available", "number"),
      col("minStock", "Min", "number"),
      col("reorderLevel", "Reorder level", "number"),
      col("reorderQuantity", "Reorder qty", "number"),
      col("stockStatus", "Status", "status"),
      col("supplier", "Supplier"),
    ],
  },
  {
    id: "stock-movements",
    title: "Stock Movement Ledger",
    description: "Receipts, issues, transfers, adjustments, reservations, and releases.",
    category: "inventory",
    icon: "ArrowLeftRight",
    permission: "inventory:view",
    sources: ["movements"],
    dateKey: "performedAt",
    columns: [
      col("inventoryItemSku", "SKU"),
      col("inventoryItemName", "Item"),
      col("type", "Type", "status"),
      col("quantity", "Quantity", "number"),
      col("unit", "Unit"),
      col("referenceType", "Reference type"),
      col("referenceId", "Reference"),
      col("performedByName", "Performed by"),
      col("performedAt", "When", "datetime"),
      col("notes", "Notes"),
    ],
  },
  {
    id: "stock-reservation",
    title: "Reserved vs Available Stock",
    description: "Items with reserved quantity - production holds versus free stock.",
    category: "inventory",
    icon: "Boxes",
    permission: "inventory:view",
    sources: ["inventory"],
    columns: [
      col("sku", "SKU"),
      col("name", "Item"),
      col("warehouse", "Warehouse"),
      col("quantityOnHand", "On hand", "number"),
      col("quantityReserved", "Reserved", "number"),
      col("quantityAvailable", "Available", "number"),
      col("reservedPercent", "Reserved", "percent"),
      col("stockStatus", "Status", "status"),
    ],
  },
  {
    id: "reprocessing-batches",
    title: "Reprocessing Batch Register",
    description: "Scrap reprocessing batches with input qty, processing cost, and status.",
    category: "inventory",
    icon: "Flame",
    permission: "manufacturing:view",
    sources: ["reprocessing"],
    dateKey: "createdAt",
    columns: [
      col("batchNumber", "Batch"),
      col("status", "Status", "status"),
      col("inputScrapSku", "Input SKU"),
      col("inputScrapName", "Input"),
      col("inputQuantity", "Input qty", "number"),
      col("inputUnitCost", "Input unit cost", "currency"),
      col("totalProcessingCost", "Processing cost", "currency"),
      col("recoveredQuantity", "Recovered", "number"),
      col("processLossQuantity", "Process loss", "number"),
      col("createdByName", "Created by"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "reprocessing-yield",
    title: "Reprocessing Yield",
    description: "Recovery rate, process loss, and recovered unit cost by completed batch.",
    category: "inventory",
    icon: "Flame",
    permission: "manufacturing:view",
    sources: ["reprocessing"],
    columns: [
      col("batchNumber", "Batch"),
      col("inputScrapName", "Input"),
      col("inputQuantity", "Input qty", "number"),
      col("recoveredQuantity", "Recovered", "number"),
      col("processLossQuantity", "Loss", "number"),
      col("yieldPercent", "Yield", "percent"),
      col("totalProcessingCost", "Processing cost", "currency"),
      col("recoveredUnitCost", "Recovered unit cost", "currency"),
    ],
  },
  {
    id: "invoice-register",
    title: "Invoice Register",
    description: "Issued invoices with paid, credited, and outstanding balances.",
    category: "finance",
    icon: "Receipt",
    permission: "finance:view",
    sources: ["invoices"],
    dateKey: "issueDate",
    columns: [
      col("invoiceNumber", "Invoice"),
      col("customerName", "Customer"),
      col("salesOrderNumber", "Sales order"),
      col("status", "Status", "status"),
      col("issueDate", "Issued", "date"),
      col("dueDate", "Due", "date"),
      col("totalAmount", "Total", "currency"),
      col("amountPaid", "Paid", "currency"),
      col("amountCredited", "Credited", "currency"),
      col("outstandingAmount", "Outstanding", "currency"),
    ],
  },
  {
    id: "receivables-aging",
    title: "Receivables Aging",
    description: "Outstanding invoice balances bucketed by days past due.",
    category: "finance",
    icon: "Wallet",
    permission: "finance:view",
    sources: ["invoices"],
    columns: [
      col("invoiceNumber", "Invoice"),
      col("customerName", "Customer"),
      col("dueDate", "Due", "date"),
      col("daysPastDue", "Days past due", "number"),
      col("agingBucket", "Bucket"),
      col("outstandingAmount", "Outstanding", "currency"),
      col("status", "Status", "status"),
    ],
  },
  {
    id: "credit-notes",
    title: "Credit Note Register",
    description: "Credit notes by reason, applied amount, and remaining balance.",
    category: "finance",
    icon: "FileMinus",
    permission: "finance:view",
    sources: ["creditNotes"],
    dateKey: "issueDate",
    columns: [
      col("creditNoteNumber", "Credit note"),
      col("customerName", "Customer"),
      col("invoiceNumber", "Invoice"),
      col("status", "Status", "status"),
      col("reason", "Reason", "status"),
      col("totalAmount", "Total", "currency"),
      col("appliedAmount", "Applied", "currency"),
      col("remainingAmount", "Remaining", "currency"),
      col("issueDate", "Issued", "date"),
    ],
  },
  {
    id: "delivery-register",
    title: "Delivery Register",
    description: "All deliveries with schedule, carrier, driver, and proof of delivery.",
    category: "delivery",
    icon: "Truck",
    permission: "delivery:view",
    sources: ["deliveries"],
    dateKey: "scheduledDate",
    columns: [
      col("deliveryNumber", "Delivery"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("scheduledDate", "Scheduled", "date"),
      col("dispatchedAt", "Dispatched", "datetime"),
      col("deliveredAt", "Delivered", "datetime"),
      col("carrier", "Carrier"),
      col("driverName", "Driver"),
      col("hasProof", "POD"),
    ],
  },
  {
    id: "on-time-delivery",
    title: "On-Time Delivery",
    description: "Delivered shipments versus scheduled date, with lateness in days.",
    category: "delivery",
    icon: "Truck",
    permission: "delivery:view",
    sources: ["deliveries"],
    dateKey: "deliveredAt",
    columns: [
      col("deliveryNumber", "Delivery"),
      col("customerName", "Customer"),
      col("scheduledDate", "Scheduled", "date"),
      col("deliveredAt", "Delivered", "date"),
      col("varianceDays", "Variance days", "number"),
      col("onTime", "On time"),
      col("status", "Status", "status"),
    ],
  },
  {
    id: "delivery-exceptions",
    title: "Failed & Returned Deliveries",
    description: "Failed, returned, cancelled, and partial deliveries that need follow-up.",
    category: "delivery",
    icon: "AlertTriangle",
    permission: "delivery:view",
    sources: ["deliveries"],
    dateKey: "scheduledDate",
    columns: [
      col("deliveryNumber", "Delivery"),
      col("customerName", "Customer"),
      col("salesOrderNumber", "Sales order"),
      col("status", "Status", "status"),
      col("scheduledDate", "Scheduled", "date"),
      col("driverName", "Driver"),
      col("notes", "Notes"),
    ],
  },
  {
    id: "customer-directory",
    title: "Customer Directory",
    description: "Active customer master with type, credit terms, order count, and revenue.",
    category: "customers",
    icon: "Users",
    permission: "customers:view",
    sources: ["customers"],
    dateKey: "createdAt",
    columns: [
      col("code", "Code"),
      col("name", "Customer"),
      col("type", "Type", "status"),
      col("status", "Status", "status"),
      col("email", "Email"),
      col("phone", "Phone"),
      col("paymentTermsDays", "Payment terms (days)", "number"),
      col("creditLimit", "Credit limit", "currency"),
      col("totalOrders", "Orders", "number"),
      col("totalRevenue", "Revenue", "currency"),
    ],
  },
  {
    id: "customer-revenue",
    title: "Customer Revenue Ranking",
    description: "Customers ranked by recorded revenue and order volume.",
    category: "customers",
    icon: "Users",
    permission: "customers:view",
    sources: ["customers"],
    columns: [
      col("name", "Customer"),
      col("type", "Type", "status"),
      col("totalOrders", "Orders", "number"),
      col("totalRevenue", "Revenue", "currency"),
      col("creditLimit", "Credit limit", "currency"),
      col("status", "Status", "status"),
    ],
  },
  {
    id: "product-catalog",
    title: "Product Catalog",
    description: "Sellable products with type, current version, cost, and list price.",
    category: "products",
    icon: "Package",
    permission: "products:view",
    sources: ["products"],
    columns: [
      col("sku", "SKU"),
      col("name", "Product"),
      col("productType", "Type", "status"),
      col("categoryName", "Category"),
      col("brandName", "Brand"),
      col("status", "Status", "status"),
      col("versionLabel", "Version"),
      col("costPrice", "Cost", "currency"),
      col("basePrice", "List price", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("leadTimeDays", "Lead time (days)", "number"),
    ],
  },
  {
    id: "product-standard-cost",
    title: "Product Standard Cost",
    description: "Material, labor, machine, coating, and overhead from the current product version.",
    category: "products",
    icon: "Calculator",
    permission: "products:view",
    sources: ["products"],
    columns: [
      col("sku", "SKU"),
      col("name", "Product"),
      col("versionLabel", "Version"),
      col("materialCost", "Material", "currency"),
      col("labourCost", "Labor", "currency"),
      col("machineCost", "Machine", "currency"),
      col("coatingFinishingCost", "Coating", "currency"),
      col("overheadCost", "Overhead", "currency"),
      col("otherCost", "Other", "currency"),
      col("costPrice", "Total cost", "currency"),
      col("basePrice", "List price", "currency"),
    ],
  },
  {
    id: "audit-activity",
    title: "Audit Activity",
    description: "System audit trail of creates, updates, approvals, exports, and deletions.",
    category: "admin",
    icon: "ScrollText",
    permission: "audit_logs:view",
    sources: ["auditLogs"],
    dateKey: "timestamp",
    columns: [
      col("timestamp", "When", "datetime"),
      col("userName", "User"),
      col("action", "Action", "status"),
      col("entity", "Entity"),
      col("entityLabel", "Record"),
      col("details", "Details"),
      col("severity", "Severity", "status"),
    ],
  },
];

const REPORT_BY_ID = new Map(REPORT_DEFINITIONS.map((report) => [report.id, report]));

export function getReportDefinition(id: string): ReportDefinition | undefined {
  return REPORT_BY_ID.get(id as ReportId);
}

export function getReportsByCategory(
  reports: ReportDefinition[] = REPORT_DEFINITIONS,
): { category: ReportCategory; label: string; reports: ReportDefinition[] }[] {
  return REPORT_CATEGORIES_ORDER.map((category) => ({
    category,
    label: REPORT_CATEGORY_LABELS[category],
    reports: reports.filter((report) => report.category === category),
  })).filter((group) => group.reports.length > 0);
}

const REPORT_CATEGORIES_ORDER: ReportCategory[] = [
  "sales",
  "operations",
  "production",
  "inventory",
  "finance",
  "delivery",
  "customers",
  "products",
  "admin",
];
