import type { ReportCategory, ReportColumn, ReportDefinition, ReportId } from "@/types/report";

function col(
  key: string,
  label: string,
  type: ReportColumn["type"] = "text",
  align?: ReportColumn["align"],
): ReportColumn {
  return {
    key,
    label,
    type,
    align: align ?? (type === "number" || type === "currency" || type === "percent" ? "right" : "left"),
  };
}

export const REPORT_CATEGORY_LABELS: Record<ReportCategory, string> = {
  sales: "Sales",
  operations: "Costing & Estimation",
  production: "Production",
  inventory: "Inventory & Reprocessing",
  finance: "Finance",
  delivery: "Delivery",
  customers: "Customers",
  products: "Products",
  admin: "System",
};

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: "quotation-register",
    title: "Quotation Register",
    description: "All quotations with status, value, validity, and conversion to sales orders.",
    category: "sales",
    icon: "FileText",
    permission: "quotations:view",
    sources: ["quotations"],
    dateKey: "createdAt",
    columns: [
      col("quotationNumber", "Quotation"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("lineCount", "Lines", "number"),
      col("totalAmount", "Total", "currency"),
      col("paymentStatus", "Payment", "status"),
      col("validUntil", "Valid until", "date"),
      col("salesOrderId", "Sales order"),
      col("createdByName", "Created by"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "sales-order-register",
    title: "Sales Order Register",
    description: "All sales orders with status, payment, linked quotation, and manufacturing jobs.",
    category: "sales",
    icon: "ClipboardList",
    permission: "sales_orders:view",
    sources: ["salesOrders"],
    dateKey: "createdAt",
    columns: [
      col("orderNumber", "Order"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("quotationNumber", "Quotation"),
      col("totalAmount", "Total", "currency"),
      col("paymentStatus", "Payment", "status"),
      col("jobCount", "Jobs", "number"),
      col("requestedDeliveryDate", "Requested delivery", "date"),
      col("assignedToName", "Assigned to"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "costing-register",
    title: "Costing Request Register",
    description: "Estimation and approval requests with margin, risk, coating, and SLA.",
    category: "operations",
    icon: "Calculator",
    permission: "quotations:view",
    sources: ["costing"],
    dateKey: "requestedDate",
    columns: [
      col("requestNumber", "Request"),
      col("customerName", "Customer"),
      col("projectName", "Project"),
      col("status", "Status", "status"),
      col("riskFlag", "Risk", "status"),
      col("coatingStatus", "Coating", "status"),
      col("totalEstimate", "Estimate", "currency"),
      col("proposedPrice", "Proposed price", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("targetMargin", "Target margin", "percent"),
      col("salesOrderNumber", "Sales order"),
      col("slaRemaining", "SLA"),
    ],
  },
  {
    id: "estimation-materials",
    title: "Estimation Material Requirements",
    description: "BOM-style materials from product estimation, including waste and line cost.",
    category: "operations",
    icon: "Layers",
    permission: "quotations:view",
    sources: ["costing"],
    columns: [
      col("requestNumber", "Request"),
      col("customerName", "Customer"),
      col("sku", "SKU"),
      col("inventoryItemName", "Material"),
      col("sourceProductName", "For product"),
      col("quantity", "Qty", "number"),
      col("wastePercent", "Waste", "percent"),
      col("requiredQuantity", "Required", "number"),
      col("unit", "Unit"),
      col("unitCost", "Unit cost", "currency"),
      col("totalCost", "Line cost", "currency"),
    ],
  },
  {
    id: "production-jobs",
    title: "Production Job Register",
    description: "All production jobs with progress, dates, cost, and assignment.",
    category: "production",
    icon: "Factory",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "plannedStartDate",
    columns: [
      col("jobNumber", "Job"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("productSku", "SKU"),
      col("productName", "Product"),
      col("quantity", "Qty", "number"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("progressPercent", "Progress", "percent"),
      col("estimatedCost", "Estimated cost", "currency"),
      col("actualCost", "Actual cost", "currency"),
      col("plannedEndDate", "Due", "date"),
      col("assignedToName", "Supervisor"),
    ],
  },
  {
    id: "quality-inspections",
    title: "Quality Inspection Report",
    description: "QC results, inspector, checklist pass rate, and linked production job.",
    category: "production",
    icon: "ShieldCheck",
    permission: "manufacturing:view",
    sources: ["jobs"],
    dateKey: "inspectedAt",
    columns: [
      col("jobNumber", "Job"),
      col("inspectionNumber", "Inspection"),
      col("productName", "Product"),
      col("customerName", "Customer"),
      col("status", "Result", "status"),
      col("inspectorName", "Inspector"),
      col("checklistTotal", "Checks", "number"),
      col("checklistPassed", "Passed", "number"),
      col("passRate", "Pass rate", "percent"),
      col("inspectedAt", "Inspected", "datetime"),
      col("notes", "Notes"),
    ],
  },
  {
    id: "ready-to-ship",
    title: "Ready to Ship",
    description: "Finished jobs checked against deliveries still waiting to ship.",
    category: "production",
    icon: "PackageCheck",
    permission: "manufacturing:view",
    sources: ["jobs", "deliveries", "salesOrders"],
    dateKey: "actualEndDate",
    columns: [
      col("jobNumber", "Job"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("productName", "Product"),
      col("quantity", "Finished", "number"),
      col("remainingQuantity", "To ship", "number"),
      col("shippedQuantity", "Shipped", "number"),
      col("shipStatus", "Ship check", "status"),
      col("actualEndDate", "Completed", "date"),
      col("actualCost", "Actual cost", "currency"),
    ],
  },
  {
    id: "stock-valuation",
    title: "Stock On Hand & Valuation",
    description: "On-hand, reserved, and available quantities with inventory value at cost.",
    category: "inventory",
    icon: "Warehouse",
    permission: "inventory:view",
    sources: ["inventory"],
    columns: [
      col("sku", "SKU"),
      col("name", "Item"),
      col("itemType", "Type", "status"),
      col("warehouse", "Warehouse"),
      col("location", "Location"),
      col("quantityOnHand", "On hand", "number"),
      col("quantityReserved", "Reserved", "number"),
      col("quantityAvailable", "Available", "number"),
      col("unit", "Unit"),
      col("costPrice", "Cost", "currency"),
      col("stockValue", "Stock value", "currency"),
      col("stockStatus", "Stock status", "status"),
    ],
  },
  {
    id: "stock-movements",
    title: "Stock Movement Ledger",
    description: "Receipts, issues, transfers, adjustments, reservations, and releases.",
    category: "inventory",
    icon: "ArrowLeftRight",
    permission: "inventory:view",
    sources: ["movements"],
    dateKey: "performedAt",
    columns: [
      col("inventoryItemSku", "SKU"),
      col("inventoryItemName", "Item"),
      col("type", "Type", "status"),
      col("quantity", "Quantity", "number"),
      col("unit", "Unit"),
      col("referenceType", "Reference type"),
      col("referenceId", "Reference"),
      col("performedByName", "Performed by"),
      col("performedAt", "When", "datetime"),
      col("notes", "Notes"),
    ],
  },
  {
    id: "reprocessing-batches",
    title: "Reprocessing Batch Register",
    description: "Scrap reprocessing batches with input qty, processing cost, and status.",
    category: "inventory",
    icon: "Flame",
    permission: "manufacturing:view",
    sources: ["reprocessing"],
    dateKey: "createdAt",
    columns: [
      col("batchNumber", "Batch"),
      col("status", "Status", "status"),
      col("inputScrapSku", "Input SKU"),
      col("inputScrapName", "Input"),
      col("inputQuantity", "Input qty", "number"),
      col("inputUnitCost", "Input unit cost", "currency"),
      col("totalProcessingCost", "Processing cost", "currency"),
      col("recoveredQuantity", "Recovered", "number"),
      col("processLossQuantity", "Process loss", "number"),
      col("createdByName", "Created by"),
      col("createdAt", "Created", "date"),
    ],
  },
  {
    id: "low-stock",
    title: "Low Stock & Reorder",
    description: "Items at or below reorder level, with suggested reorder quantity.",
    category: "inventory",
    icon: "AlertTriangle",
    permission: "inventory:view",
    sources: ["inventory"],
    columns: [
      col("sku", "SKU"),
      col("name", "Item"),
      col("warehouse", "Warehouse"),
      col("quantityAvailable", "Available", "number"),
      col("minStock", "Min", "number"),
      col("reorderLevel", "Reorder level", "number"),
      col("reorderQuantity", "Reorder qty", "number"),
      col("stockStatus", "Status", "status"),
      col("supplier", "Supplier"),
    ],
  },
  {
    id: "invoice-register",
    title: "Invoice Register",
    description: "Issued invoices with paid, credited, and outstanding balances.",
    category: "finance",
    icon: "Receipt",
    permission: "finance:view",
    sources: ["invoices"],
    dateKey: "issueDate",
    columns: [
      col("invoiceNumber", "Invoice"),
      col("customerName", "Customer"),
      col("salesOrderNumber", "Sales order"),
      col("status", "Status", "status"),
      col("issueDate", "Issued", "date"),
      col("dueDate", "Due", "date"),
      col("totalAmount", "Total", "currency"),
      col("amountPaid", "Paid", "currency"),
      col("amountCredited", "Credited", "currency"),
      col("outstandingAmount", "Outstanding", "currency"),
    ],
  },
  {
    id: "credit-notes",
    title: "Credit Note Register",
    description: "Credit notes by reason, applied amount, and remaining balance.",
    category: "finance",
    icon: "FileMinus",
    permission: "finance:view",
    sources: ["creditNotes"],
    dateKey: "issueDate",
    columns: [
      col("creditNoteNumber", "Credit note"),
      col("customerName", "Customer"),
      col("invoiceNumber", "Invoice"),
      col("status", "Status", "status"),
      col("reason", "Reason", "status"),
      col("totalAmount", "Total", "currency"),
      col("appliedAmount", "Applied", "currency"),
      col("remainingAmount", "Remaining", "currency"),
      col("issueDate", "Issued", "date"),
    ],
  },
  {
    id: "delivery-register",
    title: "Delivery Register",
    description: "All deliveries with schedule, carrier, driver, and proof of delivery.",
    category: "delivery",
    icon: "Truck",
    permission: "delivery:view",
    sources: ["deliveries"],
    dateKey: "scheduledDate",
    columns: [
      col("deliveryNumber", "Delivery"),
      col("salesOrderNumber", "Sales order"),
      col("customerName", "Customer"),
      col("status", "Status", "status"),
      col("priority", "Priority", "status"),
      col("scheduledDate", "Scheduled", "date"),
      col("dispatchedAt", "Dispatched", "datetime"),
      col("deliveredAt", "Delivered", "datetime"),
      col("carrier", "Carrier"),
      col("driverName", "Driver"),
      col("hasProof", "POD"),
    ],
  },
  {
    id: "customer-directory",
    title: "Customer Directory",
    description: "Active customer master with type, credit terms, order count, and revenue.",
    category: "customers",
    icon: "Users",
    permission: "customers:view",
    sources: ["customers"],
    dateKey: "createdAt",
    columns: [
      col("code", "Code"),
      col("name", "Customer"),
      col("type", "Type", "status"),
      col("status", "Status", "status"),
      col("email", "Email"),
      col("phone", "Phone"),
      col("paymentTermsDays", "Payment terms (days)", "number"),
      col("creditLimit", "Credit limit", "currency"),
      col("totalOrders", "Orders", "number"),
      col("totalRevenue", "Revenue", "currency"),
    ],
  },
  {
    id: "product-catalog",
    title: "Product Catalog",
    description: "Sellable products with type, current version, cost, and list price.",
    category: "products",
    icon: "Package",
    permission: "products:view",
    sources: ["products"],
    columns: [
      col("sku", "SKU"),
      col("name", "Product"),
      col("productType", "Type", "status"),
      col("categoryName", "Category"),
      col("brandName", "Brand"),
      col("status", "Status", "status"),
      col("versionLabel", "Version"),
      col("costPrice", "Cost", "currency"),
      col("basePrice", "List price", "currency"),
      col("marginPercent", "Margin", "percent"),
      col("leadTimeDays", "Lead time (days)", "number"),
    ],
  },
  {
    id: "audit-activity",
    title: "Audit Activity",
    description: "System audit trail of creates, updates, approvals, exports, and deletions.",
    category: "admin",
    icon: "ScrollText",
    permission: "audit_logs:view",
    sources: ["auditLogs"],
    dateKey: "timestamp",
    columns: [
      col("timestamp", "When", "datetime"),
      col("userName", "User"),
      col("action", "Action", "status"),
      col("entity", "Entity"),
      col("entityLabel", "Record"),
      col("details", "Details"),
      col("severity", "Severity", "status"),
    ],
  },
];

const REPORT_BY_ID = new Map(REPORT_DEFINITIONS.map((report) => [report.id, report]));

export function getReportDefinition(id: string): ReportDefinition | undefined {
  return REPORT_BY_ID.get(id as ReportId);
}

export function getReportsByCategory(
  reports: ReportDefinition[] = REPORT_DEFINITIONS,
): { category: ReportCategory; label: string; reports: ReportDefinition[] }[] {
  return REPORT_CATEGORIES_ORDER.map((category) => ({
    category,
    label: REPORT_CATEGORY_LABELS[category],
    reports: reports.filter((report) => report.category === category),
  })).filter((group) => group.reports.length > 0);
}

const REPORT_CATEGORIES_ORDER: ReportCategory[] = [
  "sales",
  "operations",
  "production",
  "inventory",
  "finance",
  "delivery",
  "customers",
  "products",
  "admin",
];
